In [1]:
import pandas as pd
import geopandas as gpd 
import matplotlib.pyplot as plt

In [2]:
dem = gpd.read_file('data/2018-census-christchurch.shp') 
dem

,SA12018_V1,C06_CURPop,C13_CURPop,C18_CURPop,C06_CNPop,C13_CNPop,C18_CNPop,C18_UnitRe,C18_Unit_1,C18_Unit_2,...,C18_Maor_2,C18_Maor_3,C18_Maor_4,C18_Maor_5,LANDWATER,LANDWATER_,LAND_AREA_,AREA_SQ_KM,SHAPE_Leng,geometry
0,7024225,162,147,153,159,192,162,135,3,18,...,3,153,0,153,12,Mainland,0.210451,0.210451,3133.367683,"POLYGON ((1572393.269 5195712.576, 1572411.115..."
1,7024282,198,189,201,195,186,192,171,6,21,...,15,201,0,201,12,Mainland,1.002873,1.002873,4451.861761,"POLYGON ((1573364.898 5193879.490, 1573199.176..."
2,7024477,150,165,159,153,168,150,132,9,21,...,6,159,0,159,12,Mainland,0.056614,0.056614,954.901198,"POLYGON ((1570739.224 5189502.009, 1570776.713..."
3,7024284,150,195,201,150,204,201,183,0,21,...,6,201,0,201,12,Mainland,5.277723,5.277723,12375.786099,"POLYGON ((1573973.709 5188313.452, 1573936.848..."
4,7024345,117,117,111,117,117,108,96,3,9,...,3,111,0,111,12,Mainland,0.041789,0.041789,1508.818156,"POLYGON ((1566784.460 5185033.498, 1566817.679..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2536,7026980,126,165,210,123,171,225,192,0,18,...,9,210,0,210,12,Mainland,16.050081,16.050081,19276.638033,"POLYGON ((1566422.243 5170681.822, 1566442.034..."
2537,7026981,165,174,186,171,183,186,171,3,15,...,9,186,0,186,12,Mainland,11.379448,11.379448,21810.942128,"POLYGON ((1565602.376 5166737.852, 1565681.512..."
2538,7027013,123,135,129,120,135,126,123,3,6,...,0,129,0,129,12,Mainland,8.450195,8.450195,15428.976833,"POLYGON ((1559996.908 5163688.479, 1560232.502..."
2539,7027014,153,195,150,150,195,153,135,0,15,...,3,150,0,150,12,Mainland,23.401956,23.401956,43192.911756,"POLYGON ((1557874.130 5161850.609, 1558485.046..."
2540,7027015,156,159,153,156,156,150,135,6,12,...,0,153,0,153,12,Mainland,8.126060,8.126060,13969.173324,"POLYGON ((1560556.851 5164226.648, 1560571.453..."

In [3]:
dem.head()
dem.loc[0]

SA12018_V1                                              7024225
C06_CURPop                                                  162
C13_CURPop                                                  147
C18_CURPop                                                  153
C06_CNPop                                                   159
                                    ...
LANDWATER_                                             Mainland
LAND_AREA_                                             0.210451
AREA_SQ_KM                                             0.210451
SHAPE_Leng                                              3133.37
geometry      POLYGON ((1572393.269100003 5195712.575900001,...
Name: 0, Length: 440, dtype: object

In [5]:
dem.shape

(2541, 440)

In [6]:
dem.columns

Index(['SA12018_V1', 'C06_CURPop', 'C13_CURPop', 'C18_CURPop', 'C06_CNPop',
       'C13_CNPop', 'C18_CNPop', 'C18_UnitRe', 'C18_Unit_1', 'C18_Unit_2',
       ...
       'C18_Maor_2', 'C18_Maor_3', 'C18_Maor_4', 'C18_Maor_5', 'LANDWATER',
       'LANDWATER_', 'LAND_AREA_', 'AREA_SQ_KM', 'SHAPE_Leng', 'geometry'],
      dtype='object', length=440)

In [ ]:
esl = gpd.read_file('')